/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package discordbot;

import java.io.IOException;

import javax.security.auth.login.LoginException;
import net.dv8tion.jda.api.hooks.ListenerAdapter;

public class Main extends ListenerAdapter {
	private static final String PATH = "./src/main/resources/token.txt";

	public static void main(String[] args)
			throws LoginException, InterruptedException, IOException {
		DiscordToken token = new DiscordToken(PATH);
		System.out.println("botToken : " + token.getBotToken());

		DiscordApi api = new DiscordApi(token.getBotToken());
		api.botStart();
	}
}
