/*
 * This Java source file was generated by the Gradle 'init' task.
 *
 * discord bot address
 * https://discord.com/developers/applications
 */
package discordbot;

// import net.dv8tion.jda.api.JDA;
// import net.dv8tion.jda.api.JDABuilder;
// import net.dv8tion.jda.api.OnlineStatus;
// import net.dv8tion.jda.api.entities.Activity;
// import net.dv8tion.jda.api.hooks.ListenerAdapter;
// import net.dv8tion.jda.api.requests.GatewayIntent;
import net.dv8tion.jda.api.hooks.*;
import net.dv8tion.jda.api.*;
import net.dv8tion.jda.api.requests.*;
import net.dv8tion.jda.api.utils.cache.CacheFlag;

import javax.security.auth.login.LoginException;
import java.io.IOException;

public class Main extends ListenerAdapter {
	private static final String PATH = "./app/src/main/resources/token.txt";

	// https://github.com/DV8FromTheWorld/JDA

	public static void main(String[] args)
			throws LoginException, IOException {
		DiscordToken token = new DiscordToken(PATH);
		System.out.println("botToken : " + token.getBotToken());

		// JDA 객체 생성
		// https://lovelyunsh.tistory.com/202
		JDA jda = JDABuilder.createDefault(token.getBotToken())
			// .setActivity(Activity.playing("Type /help"))
			.enableIntents(GatewayIntent.GUILD_MEMBERS)
			.enableIntents(GatewayIntent.GUILD_MESSAGES)
            .enableIntents(GatewayIntent.DIRECT_MESSAGES)
			.enableIntents(GatewayIntent.GUILD_PRESENCES)
			.enableCache(CacheFlag.ACTIVITY)
				.build();

		// jda.upsertCommand("help", "help test").queue();

		// bot Online 표시
		jda.getPresence().setStatus(OnlineStatus.ONLINE);

		// bot Event 설정
		BotEvent botEvent = new BotEvent();

		// botEvent Status 설정
		jda.addEventListener(botEvent);

		System.out.println("Bot Run Success");
	}
}
