/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package discordbot;

import org.junit.jupiter.api.Test;

class MainTest {
	@Test
	void appHasAGreeting() {
		Main classUnderTest = new Main();
		System.out.println("Test Example");
		// assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
	}
}
